export const musicList = [
  {
    id: 1,
    artistName: "SHOUSE",
    musicName: "Love Tonight",
    musicPath: "Lovetonight.mp3",
    imagePath: "LoveTonight.png",
    duration: 171,
  },
  {
    id: 2,
    artistName: "Mehman Huseynov",
    musicName: "Hani Bes",
    musicPath: "Mehman Huseynov- Hani Bes (Official Video Klip 2021 ).mp3",
    imagePath: "hanibes.jpg",
    duration: 266,
  },
  {
    id: 3,
    artistName: "Monica Belluci",
    musicName: "Malena",
    musicPath: "Monica Belluci - Malena.mp3",
    imagePath: "monica.webp",
    duration: 231,
  },
  {
    id: 4,
    artistName: "Namiq Qaracuxurlu",
    musicName: "Cavanligimin Ogrusu",
    musicPath: "namiq.mp3",
    imagePath: "namiq.jpg",
    duration: 63,
  },
  {
    id: 5,
    artistName: "Savai",
    musicName: "Dark Life",
    musicPath: "Savai - Dark Life (Instrumental).mp3",
    imagePath: "darklife.jpg",
    duration: 194,
  },
  {
    id: 6,
    artistName: "Tom Odell",
    musicName: "Another Love",
    musicPath: "Tom Odell - Another Love (Official Video).mp3",
    imagePath: "another.jpg",
    duration: 247,
  },
  {
    id: 7,
    artistName: "Xpert",
    musicName: "Və bir də",
    musicPath: "Xpert - Və bir də (Official Music Video).mp3",
    imagePath: "expert.jpg",
    duration: 219,
  },
  {
    id: 8,
    artistName: "Imagine Dragons",
    musicName: "Bones",
    musicPath: "Bones.mp3",
    imagePath: "images.jpg",
    duration: 162,
  },
  {
    id: 9,
    artistName: "Jah Khalib",
    musicName: "Медина",
    musicPath: "Jah Khalib - Медина.mp3",
    imagePath: "JahKhalib.jpg",
    duration: 240,
  },
  {
    id: 10,
    artistName: "Hadise",
    musicName: "Prenses",
    musicPath: "hadise.mp3",
    imagePath: "hadise.jpg",
    duration: 180,
  },
];
